name: deus_mobile
description: The future of mobile trading.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # BACKEND
  http: ^0.12.2
  json_annotation: ^3.1.0
  equatable: ^1.2.6
  web3dart: ^2.0.0-dev.9
  bip39: ^1.0.3
  hex: ^0.1.2
  tweetnacl: ^0.3.2
  get_it: ^5.0.6
  flutter_bloc: ^6.1.3
  string_validator: ^0.1.4
  flutter_secure_storage: ^4.1.0

  # FRONTEND
  fluttertoast: ^7.1.6
  flutter_hooks: ^0.9.0
  flutter_svg: ^0.19.3
  shimmer_animation: ^0.0.9+1
  shared_preferences: ^2.0.4
  flutter_icons: ^1.1.0
  flushbar: ^1.10.4
  page_transition: ^1.1.5
  provider: ^4.3.1
  flutter_device_type: ^0.2.0
  url_launcher:
  outline_gradient_button: ^1.0.0+2
  flutter_countdown_timer: ^3.0.0
  flutter_svg_provider: ^0.1.8
  stream_transform: ^0.0.19
  fl_chart: ^0.12.3
  vibration: ^1.7.3

dependency_overrides:
  analyzer: ^0.41.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    # FRONTEND
    - assets/images/
    - assets/images/currencies/
    - assets/images/stocks/
    - assets/images/icons/
    - assets/launcher_icon/
    - assets/blur_screens/
    # BACKEND
    - assets/deus_data/ # data of tokens, contract ABI/functions etc.
  
flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/deus_dea.png"

  fonts:
    - family: Monument
      fonts:
        - asset: assets/fonts/monument-regular.ttf
          weight: 300

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
